### ISSUE TITLE
Autogenerated config doesn't work

### ISSUE THREAD

**Issue by eu9ene** [mozilla/translations#941]
Run `task config-generator -- zh en --name cjk` and then run a train action with it. It generates 0 tasks.

The issue is apparently in renaming "target-stage: all" to "all-pipeline" which doesn't pass validation.

Also `    fp16: true` doesn't pass validation, it should be either quoted or removed since it duplicates the default decoding config.

**Comment by nordzilla** [comment]
That change was made in #871 due to [this comment](https://github.com/mozilla/translations/pull/871#discussion_r1792457889). 

I agree with Ben's comment, and think that `all-pipeline` is a better name.

I wasn't aware that I had broken anything, however.

How difficult would it be to update things to conform to `all-pipeline`?

**Comment by eu9ene** [comment]
My main goal now is to run training, so I'll roll it back in my branch. If we want to keep the new name we should:
- figure out why the validation on Train action fails with it: `data/target-stage must be equal to one of the allowed values` (see docs/taskcluster.md on how to run the train action)
- update config templates in `taskcluster/configs`
- probably update some other configs, for example the ones in `test/fixtures` and `tascluster/test/params`

Overall if this renaming is not that important, maybe it's easier to roll it back. It would also break all our old configs which is maybe not a big deal because we're not planning to use them as is but still.
